### PR TITLE
soulsiphon +

### PR DESCRIPTION
**Pull request by crazysmile11012**
i added a structure that functions as a tutorial of sorts (like the igloo) into the nether biomes this is the first structure out of a library of soul siphon dungeons and there variants.

### CODE REVIEW

**Comment by crazysmile11012** [comment]
note: the first picture is a debug structure (not in this commit)

**Comment by Negative-light** [comment]
This seems like an interesting idea. I think this can be forwarded to Healex for review to be added in the main mod.

**Comment by Healex2** [comment]
I have no problem with this being made, though it would be separate from the base mod.

**Comment by Negative-light** [comment]
So I wonder if this should be a mod that extends Soul Siphone similar to how Create does it or if we should have a separate release branch of Soul Siphon +

**Comment by crazysmile11012** [comment]
> So I wonder if this should be a mod that extends Soul Siphone similar to how Create does it or if we should have a separate release branch of Soul Siphon +

the original could be soulsiphon lite my fork could be advance

**Comment by Negative-light** [comment]
This could be valid. As long as we make sure to update the code between both it should be simple.
I would say we do
Soul Siphon and Soul Siphon +

**Comment by crazysmile11012** [comment]
if it is going to be soulsiphon + i should add plus features like more blocks that require souls to function 
they could be things like furnaces that run off souls as fuel 
maybe a few quality of life features

**Comment by crazysmile11012** [comment]
where did the conflicts come from i did not change anything and now there is a conflict

**Comment by crazysmile11012** [comment]
the conflicts are fixed but it says it is not (it is latterly just spacing in code)

**Comment by Negative-light** [comment]
This code will not be merged into the main codebase. Please wait for #14 to be completed so that we can decide on how forks will be managed.

**Pull request closed without merging**
